FROM osrm/osrm-backend

RUN apt-get update && \
    apt-get install -y --no-install-recommends wget && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /data
RUN wget https://download.geofabrik.de/north-america/us-latest.osm.pbf --no-check-certificate

RUN /usr/local/bin/osrm-extract -p /opt/car.lua ./us-latest.osm.pbf
RUN /usr/local/bin/osrm-partition ./us-latest.osrm
RUN /usr/local/bin/osrm-customize ./us-latest.osrm