version: "3.7"
services:
    osrm:
        build:
            context: './osrm'
            dockerfile: 'dockerfile'
        container_name: 'osrm'
        networks:
            tsp_network:
                aliases:
                - osrm
        ports:
            - "5000:5000"
        restart: always
        command: "osrm-routed --max-matching-size 1000 --max-table-size 1000 --max-viaroute-size 1000 --algorithm mld ./us-latest.osrm"
        volumes:
            - ./osrm:/data
    vroom-backend:
        build:
            context: './backend'
            dockerfile: 'dockerfile'
        restart: always
        depends_on: ['osrm']
        ports:
            - "3000:3000"
        networks:
            tsp_network:
                aliases:
                - vroom-backend
    vroom-frontend:
        build:
            context: './frontend'
            dockerfile: 'dockerfile'
        restart: always
        ports:
            - "9966:9966"
        depends_on:
            - vroom-backend
        networks:
            tsp_network:
                aliases:
                - vroom-frontend
networks:
  tsp_network:
      driver: bridge